#pragma once

enum pid_defs {
    CHARACTER_ELIWOOD = 0x01,
    CHARACTER_HECTOR = 0x02,
    CHARACTER_LYN_TUTORIAL = 0x03,

    CHARACTER_OSWIN = 0x0B,

    CHARACTER_NINO = 0x14,

    CHARACTER_HAWKEYE = 0x22,
    CHARACTER_MATTHEW = 0x23,
    CHARACTER_NILS = 0x26,
    CHARACTER_ATHOS = 0x27,
    CHARACTER_MERLINUS = 0x28,

    CHARACTER_LYN = 0x2D,

    CHARACTER_FIREDRAGON = 0x86,

    CHARACTER_DA = 0xDA,

    CHARACTER_WALL = 0xFC,
    CHARACTER_SNAG = 0xFD,
};
