#pragma once

enum pid_defs {
    CHARACTER_ELIWOOD = 0x01,
    CHARACTER_HECTOR = 0x02,
    CHARACTER_LYN = 0x03,
    CHARACTER_28 = 0x28,

    CHARACTER_FIREDRAGON = 0x86,

    CHARACTER_DA = 0xDA,

    CHARACTER_WALL = 0xFC,
    CHARACTER_SNAG = 0xFD,
};
