#pragma once

#define CHR_SIZE 0x20
#define CHR_LINE 0x20

enum {
    BGPAL_TEXT_DEFAULT    = 0,
    BGPAL_WINDOWFRAME     = 1,
    BGPAL_TALK            = 2,
    BGPAL_TALK_BUBBLE     = 3,
    BGPAL_ICONS           = 4, // .. 5
    BGPAL_TILESET         = 6, // .. 15

    BGPAL_STATSCREEN_6    = 6,
    BGPAL_MURALBACKGROUND = 14,

    STATSCREEN_BGPAL_HALO = 1,
    STATSCREEN_BGPAL_2 = 2,
    STATSCREEN_BGPAL_3 = 3,
    STATSCREEN_BGPAL_ITEMICONS = 4,
    STATSCREEN_BGPAL_EXTICONS = 5,
    STATSCREEN_BGPAL_6 = 6,
    STATSCREEN_BGPAL_7 = 7,
    STATSCREEN_BGPAL_FACE = 11,
    STATSCREEN_BGPAL_BACKGROUND = 12, // 4 palettes

    BGPAL_STATSCREEN_EQUIPSTATFRAME = 7,
    BGPAL_STATSCREEN_FACE = 13,
};

enum {
    BGCHR_WINDOWFRAME = 0,

    BGCHR_STATSCREEN_EQUIPSTATFRAME = 0x60,
    BGCHR_STATSCREEN_FACE = 0xE0,
    BGCHR_STATSCREEN_BACKMURAL = 0x180,
    BGCHR_STATSCREEN_EQUIPMENTLABEL = 0x270,

    BGCHR_ICON_END   = 0x300,
};

enum objchr_idx {
    OBCHR_FACE_DEFAULT2 = 0x200,
    OBCHR_FACE_DEFAULT1 = 0x280,
    OBCHR_FACE_DEFAULT0 = 0x300,
    OBCHR_FACE_DEFAULT3 = 0x380,

    OBCHR_STATSCREEN_60  = 0x60,
    OBCHR_STATSCREEN_240 = 0x240,
};

enum objpal_idx {
    OBPAL_FACE_DEFAULT0 = 6,
    OBPAL_FACE_DEFAULT1 = 7,
    OBPAL_FACE_DEFAULT2 = 8,
    OBPAL_FACE_DEFAULT3 = 9,

    OBPAL_STATSCREEN_WINDOWFRAME = 2,
    OBPAL_STATSCREEN_PAGENAME = 3,
    OBPAL_STATSCREEN_SPRITES = 4,
    OBPAL_STATSCREEN_10 = 10,

    OBPAL_MAPSPRITES = 12,
    OBPAL_UNITSPRITE_BLUE = OBPAL_MAPSPRITES + 0,
    OBPAL_UNITSPRITE_RED = OBPAL_MAPSPRITES + 1,
    OBPAL_UNITSPRITE_GREEN = OBPAL_MAPSPRITES + 2,
    OBPAL_UNITSPRITE_GRAY = OBPAL_MAPSPRITES + 3,
};
