#include "gbafe.h"

CONST_DATA u8 MoveScr_08D83828[] = {
    MOVE_CMD_SET_SPEED, 14,
    MOVE_CMD_MOVE_LEFT,
    MOVE_CMD_MOVE_LEFT,
    MOVE_CMD_MOVE_UP,
    MOVE_CMD_MOVE_UP,
    MOVE_CMD_MOVE_UP,
    MOVE_CMD_MOVE_UP,
    MOVE_CMD_MOVE_UP,
    MOVE_CMD_MOVE_LEFT,
    MOVE_CMD_MOVE_LEFT,
    MOVE_CMD_MOVE_UP,
    MOVE_CMD_HALT,
};

CONST_DATA u8 MoveScr_08D83835[] = {
    MOVE_CMD_SET_SPEED, 16,
    MOVE_CMD_MOVE_DOWN,
    MOVE_CMD_MOVE_DOWN,
    MOVE_CMD_MOVE_RIGHT,
    MOVE_CMD_MOVE_DOWN,
    MOVE_CMD_MOVE_DOWN,
    MOVE_CMD_HALT,
};

CONST_DATA u8 MoveScr_08D8383D[] = {
    MOVE_CMD_SET_SPEED, 16,
    MOVE_CMD_MOVE_DOWN,
    MOVE_CMD_MOVE_DOWN,
    MOVE_CMD_MOVE_LEFT,
    MOVE_CMD_HALT,
};

CONST_DATA u8 MoveScr_08D83843[] = {
    MOVE_CMD_SET_SPEED, 16,
    MOVE_CMD_MOVE_RIGHT,
    MOVE_CMD_MOVE_UP,
    MOVE_CMD_MOVE_UP,
    MOVE_CMD_MOVE_RIGHT,
    MOVE_CMD_MOVE_UP,
    MOVE_CMD_HALT,
};

CONST_DATA u8 MoveScr_08D8384B[] = {
    MOVE_CMD_SET_SPEED, 16,
    MOVE_CMD_MOVE_UP,
    MOVE_CMD_MOVE_UP,
    MOVE_CMD_MOVE_UP,
    MOVE_CMD_HALT,
};
