#include "gbafe.h"

int CONST_DATA gHelpTextIds_PrepItemScreen[] = {
	MSG_38A,
	MSG_38E,
	MSG_38F,
	MSG_390,
	MSG_38C,
	MSG_38D,
};

struct ProcCmd CONST_DATA ProcScr_PrepItemScreen[] = {
    PROC_YIELD,
    PROC_CALL(PrepItemScreen_Init),
    PROC_CALL(PrepItemScreen_SetupGfx),
    PROC_CALL(PrepItemScreen_Reinit),
    PROC_CALL_ARG(NewFadeIn, 16),
    PROC_WHILE(FadeInExists),
    PROC_YIELD,
    PROC_GOTO(1),
PROC_LABEL(0),
    PROC_CALL(PrepItemScreen_Reinit),
PROC_LABEL(1),
    PROC_REPEAT(sub_80926F0),
    PROC_CALL(DisableAllGfx),
    PROC_YIELD,
    PROC_CALL(PrepItemScreen_StartStatScreen),
    PROC_YIELD,
    PROC_CALL(PrepItemScreen_ResumeFromStatScreen),
    PROC_CALL(PrepItemScreen_Reinit),
    PROC_YIELD,
    PROC_CALL(EnableAllGfx),
    PROC_GOTO(1),
PROC_LABEL(2),
    PROC_CALL(sub_8092A1C),
    PROC_CALL(PrepItemScreen_DrawFunds),
    PROC_YIELD,
    PROC_CALL(sub_8092A9C),
PROC_LABEL(3),
    PROC_REPEAT(sub_8092B30),
PROC_LABEL(4),
    PROC_CALL(PrepItemScreen_HideFunds),
    PROC_CALL(sub_8092EDC),
    PROC_YIELD,
    PROC_CALL(sub_8093004),
PROC_LABEL(5),
    PROC_REPEAT(PrepItemScreen_Loop_MainKeyHandler),
    PROC_CALL(DisableAllGfx),
    PROC_YIELD,
    PROC_CALL(PrepItemScreen_StartStatScreen),
    PROC_YIELD,
    PROC_CALL(PrepItemScreen_ResumeFromStatScreen),
    PROC_CALL(sub_8092EDC),
    PROC_CALL(sub_8093004),
    PROC_YIELD,
    PROC_CALL(EnableAllGfx),
    PROC_GOTO(5),
PROC_LABEL(6),
    PROC_CALL_ARG(NewFadeOut, 16),
    PROC_WHILE(FadeOutExists),
    PROC_CALL(StartPrepItemTradeScreen),
    PROC_YIELD,
    PROC_CALL(PrepItemScreen_SetupGfx),
    PROC_YIELD,
    PROC_CALL(sub_8092EDC),
    PROC_CALL(sub_8093004),
    PROC_CALL_ARG(NewFadeIn, 16),
    PROC_WHILE(FadeInExists),
    PROC_GOTO(5),
PROC_LABEL(8),
    PROC_CALL_ARG(NewFadeOut, 16),
    PROC_WHILE(FadeOutExists),
    PROC_CALL(PrepItemScreen_OnEnd),
    PROC_CALL(sub_80931E0),
    PROC_YIELD,
    PROC_CALL(PrepItemScreen_SetupGfx),
    PROC_YIELD,
    PROC_CALL(sub_8092AF8),
    PROC_CALL(sub_8092A1C),
    PROC_CALL(PrepItemScreen_DrawFunds),
    PROC_CALL(sub_8092A9C),
    PROC_CALL_ARG(NewFadeIn, 16),
    PROC_WHILE(FadeInExists),
    PROC_GOTO(3),
PROC_LABEL(9),
    PROC_CALL_ARG(NewFadeOut, 16),
    PROC_WHILE(FadeOutExists),
    PROC_CALL(PrepItemScreen_OnEnd),
    PROC_CALL(sub_8093198),
    PROC_YIELD,
    PROC_CALL(PrepItemScreen_SetupGfx),
    PROC_YIELD,
    PROC_CALL(sub_8092AF8),
    PROC_CALL(sub_8092A1C),
    PROC_CALL(PrepItemScreen_DrawFunds),
    PROC_CALL(sub_8092A9C),
    PROC_CALL_ARG(NewFadeIn, 16),
    PROC_WHILE(FadeInExists),
    PROC_GOTO(3),
PROC_LABEL(10),
    PROC_CALL_ARG(NewFadeOut, 16),
    PROC_WHILE(FadeOutExists),
    PROC_CALL(PrepItemScreen_OnEnd),
    PROC_CALL(sub_80931B0),
    PROC_YIELD,
    PROC_CALL(PrepItemScreen_SetupGfx),
    PROC_YIELD,
    PROC_CALL(sub_8092AF8),
    PROC_CALL(sub_8092A1C),
    PROC_CALL(PrepItemScreen_DrawFunds),
    PROC_CALL(sub_8092A9C),
    PROC_CALL_ARG(NewFadeIn, 16),
    PROC_WHILE(FadeInExists),
    PROC_GOTO(3),
PROC_LABEL(11),
    PROC_CALL_ARG(NewFadeOut, 16),
    PROC_WHILE(FadeOutExists),
    PROC_CALL(PrepItemScreen_OnEnd),
    PROC_CALL(StartPrepArmory),
    PROC_YIELD,
    PROC_CALL(PrepItemScreen_SetupGfx),
    PROC_YIELD,
    PROC_CALL(sub_8092AF8),
    PROC_CALL(sub_8092A1C),
    PROC_CALL(PrepItemScreen_DrawFunds),
    PROC_CALL(sub_8092A9C),
    PROC_CALL_ARG(NewFadeIn, 16),
    PROC_WHILE(FadeInExists),
    PROC_GOTO(3),
PROC_LABEL(12),
    PROC_CALL_ARG(NewFadeOut, 16),
    PROC_WHILE(FadeOutExists),
    PROC_CALL(PrepItemScreen_OnEnd),
    PROC_END,
};

void PrepItemScreen_OnHBlank(void)
{
    u16 vcount = REG_VCOUNT + 1;

    if (vcount > DISPLAY_HEIGHT)
        vcount = 0;

    if (vcount == 0)
        REG_BG0VOFS = 248;

    if (vcount == 72)
        REG_BG0VOFS = 252;
}

u16 CONST_DATA Sprite_08D8CD90[] =
{
    3,
    OAM0_SHAPE_16x8, OAM1_SIZE_16x8, OAM2_LAYER(2),
    OAM0_SHAPE_16x8 + OAM0_Y(8), OAM1_SIZE_16x8, OAM2_CHR(0x6) + OAM2_LAYER(2),
    OAM0_SHAPE_16x8 + OAM0_Y(16), OAM1_SIZE_16x8, OAM2_CHR(0xC) + OAM2_LAYER(2),
};

int CONST_DATA Unk_08D8CDA4 = 0x02040200; // ?
